apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  labels:
    app: ace-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace-app
  template:
    metadata:
      labels:
        app: ace-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: ace-container
        # Use custom image built in Minikube
        image: my-custom-ace:v1
        imagePullPolicy: Never
        env:
        - name: LICENSE
          value: "accept"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        command: ["/bin/bash", "-c"]
        args:
        - |
          source /opt/ibm/ace-*/server/bin/mqsiprofile
          mqsicreatebroker PROD
          mqsistart PROD
          mqsicreateexecutiongroup PROD -e prodserver
          echo "Deploying BAR file..."
          # Deploy from local image path
          mqsideploy PROD -e prodserver -a /home/aceuser/BVSRegFix2.bar -m -w 600
          echo "Broker PROD and Server prodserver started and BAR deployed."
          # Keep container alive
          tail -f /dev/null
