apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  labels:
    app: ace-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace-app
  template:
    metadata:
      labels:
        app: ace-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      volumes:
      - name: bar-storage
        persistentVolumeClaim:
          claimName: ace-bar-store
      containers:
      - name: ace-container
        image: moiz3388/ace13:latest
        env:
        - name: LICENSE
          value: "accept"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: bar-storage
          mountPath: /home/aceuser/bars
        command: ["/bin/bash", "-c"]
        args:
        - |
          source /opt/ibm/ace-*/server/bin/mqsiprofile
          echo "Starting Pod..."
          mqsicreatebroker PROD
          mqsistart PROD
          mqsicreateexecutiongroup PROD -e prodserver
          echo "Deploying BAR file..."
          # Deploy from PVC mount path
          mqsideploy PROD -e prodserver -a /home/aceuser/bars/BVSRegFix2.bar -w 600
          echo "Broker PROD and Server prodserver started and BAR deployed."
          # Keep container alive
          tail -f /dev/null
